name: 'Various checks for the repository'

on:
  push:
    branches:
      - master

jobs:
  secret-detection:
    uses: Yellow-Dog-Man/composite-actions-templates/.github/workflows/secret-detection.yml@main
    secrets: inherit
    permissions:
      contents: read
